/**
 * Seed prospect pool for NHL Draft 2026 Pick'em MVP.
 * Replace with real rankings/data before the draft — IDs are stable keys for scoring.
 */
export type NhlDraft26Prospect = {
  id: string;
  name: string;
  position: string;
  country: string;
  teamLeague: string;
  consensusRank: number;
  shortNote: string;
};

/** Demo placeholder prospects — not final 2026 rankings. */
export const NHL_DRAFT26_PROSPECTS_SEED: NhlDraft26Prospect[] = [
  {
    id: "james-hagens",
    name: "James Hagens",
    position: "C",
    country: "USA",
    teamLeague: "Boston Univ. (NCAA)",
    consensusRank: 1,
    shortNote: "Demo #1 — elite two-way center projection.",
  },
  {
    id: "matthew-schaefer",
    name: "Matthew Schaefer",
    position: "D",
    country: "CAN",
    teamLeague: "Erie (OHL)",
    consensusRank: 2,
    shortNote: "Demo #2 — top defensive prospect in class.",
  },
  {
    id: "porter-martone",
    name: "Porter Martone",
    position: "RW",
    country: "CAN",
    teamLeague: "Brampton (OHL)",
    consensusRank: 3,
    shortNote: "Demo #3 — power winger with high-end shot.",
  },
  {
    id: "gavin-mckenna",
    name: "Gavin McKenna",
    position: "LW",
    country: "CAN",
    teamLeague: "Kamloops (WHL)",
    consensusRank: 4,
    shortNote: "Demo #4 — dynamic scorer, strong edges.",
  },
  {
    id: "anton-frondell",
    name: "Anton Frondell",
    position: "C",
    country: "SWE",
    teamLeague: "Djurgården (SHL)",
    consensusRank: 5,
    shortNote: "Demo #5 — pro-ready center from Sweden.",
  },
  {
    id: "carter-george",
    name: "Carter George",
    position: "G",
    country: "CAN",
    teamLeague: "Owen Sound (OHL)",
    consensusRank: 6,
    shortNote: "Demo #6 — top goalie in consensus lists.",
  },
  {
    id: "michael-misa",
    name: "Michael Misa",
    position: "C",
    country: "CAN",
    teamLeague: "Saginaw (OHL)",
    consensusRank: 7,
    shortNote: "Demo #7 — high-skill pivot with pace.",
  },
  {
    id: "cameron-reid",
    name: "Cameron Reid",
    position: "D",
    country: "CAN",
    teamLeague: "Brantford (OHL)",
    consensusRank: 8,
    shortNote: "Demo #8 — mobile defender, strong breakout.",
  },
  {
    id: "jake-ostlie",
    name: "Jake Ostlé",
    position: "LW",
    country: "CAN",
    teamLeague: "Brandon (WHL)",
    consensusRank: 9,
    shortNote: "Demo #9 — forecheck-driven winger.",
  },
  {
    id: "luca-romanov",
    name: "Luca Romanov",
    position: "D",
    country: "CAN",
    teamLeague: "Windsor (OHL)",
    consensusRank: 10,
    shortNote: "Demo #10 — physical RD with PP upside.",
  },
  {
    id: "cole-bennett",
    name: "Cole Bennett",
    position: "C",
    country: "USA",
    teamLeague: "Boston Coll. (NCAA)",
    consensusRank: 11,
    shortNote: "Demo #11 — playmaking center.",
  },
  {
    id: "viktor-soderqvist",
    name: "Viktor Söderqvist",
    position: "RW",
    country: "SWE",
    teamLeague: "HV71 (SHL)",
    consensusRank: 12,
    shortNote: "Demo #12 — skilled Swedish winger.",
  },
  {
    id: "nate-danielson",
    name: "Nate Danielson",
    position: "C",
    country: "CAN",
    teamLeague: "Everett (WHL)",
    consensusRank: 13,
    shortNote: "Demo #13 — two-way forward, strong details.",
  },
  {
    id: "emil-pettersson",
    name: "Emil Pettersson",
    position: "D",
    country: "SWE",
    teamLeague: "Rögle (SHL)",
    consensusRank: 14,
    shortNote: "Demo #14 — puck-moving LD.",
  },
  {
    id: "jackson-hallum",
    name: "Jackson Hallum",
    position: "D",
    country: "USA",
    teamLeague: "Omaha (USHL)",
    consensusRank: 15,
    shortNote: "Demo #15 — steady defensive game.",
  },
  {
    id: "ryan-lin",
    name: "Ryan Lin",
    position: "LW",
    country: "USA",
    teamLeague: "USNTDP",
    consensusRank: 16,
    shortNote: "Demo #16 — speed and compete.",
  },
  {
    id: "oliver-moore",
    name: "Oliver Moore",
    position: "C",
    country: "USA",
    teamLeague: "Chicago (USHL)",
    consensusRank: 17,
    shortNote: "Demo #17 — responsible two-way C.",
  },
  {
    id: "trevor-kuntar",
    name: "Trevor Kuntar",
    position: "RW",
    country: "USA",
    teamLeague: "Boston Univ. (NCAA)",
    consensusRank: 18,
    shortNote: "Demo #18 — net-front finisher.",
  },
  {
    id: "ben-kindel",
    name: "Ben Kindel",
    position: "C",
    country: "CAN",
    teamLeague: "Calgary (WHL)",
    consensusRank: 19,
    shortNote: "Demo #19 — skilled small-area play.",
  },
  {
    id: "maxim-strbak",
    name: "Maxim Štrbák",
    position: "D",
    country: "SVK",
    teamLeague: "Michigan State (NCAA)",
    consensusRank: 20,
    shortNote: "Demo #20 — size and reach on the blue line.",
  },
  {
    id: "carter-amaya",
    name: "Carter Amaya",
    position: "G",
    country: "USA",
    teamLeague: "USNTDP",
    consensusRank: 21,
    shortNote: "Demo #21 — athletic goalie prospect.",
  },
  {
    id: "luca-romanelli",
    name: "Luca Romanelli",
    position: "RW",
    country: "CAN",
    teamLeague: "Ottawa (OHL)",
    consensusRank: 22,
    shortNote: "Demo #22 — shot-first winger.",
  },
  {
    id: "henrik-hofer",
    name: "Henrik Hofer",
    position: "LW",
    country: "GER",
    teamLeague: "Mannheim (DEL)",
    consensusRank: 23,
    shortNote: "Demo #23 — European scoring winger.",
  },
  {
    id: "sam-whitney",
    name: "Sam Whitney",
    position: "D",
    country: "CAN",
    teamLeague: "Seattle (WHL)",
    consensusRank: 24,
    shortNote: "Demo #24 — transitional defender.",
  },
  {
    id: "aidan-park",
    name: "Aidan Park",
    position: "C",
    country: "CAN",
    teamLeague: "Kelowna (WHL)",
    consensusRank: 25,
    shortNote: "Demo #25 — faceoff and defensive value.",
  },
  {
    id: "marcus-nilsson",
    name: "Marcus Nilsson",
    position: "RW",
    country: "SWE",
    teamLeague: "Luleå (SHL)",
    consensusRank: 26,
    shortNote: "Demo #26 — pro experience in Sweden.",
  },
  {
    id: "tyler-young",
    name: "Tyler Young",
    position: "LW",
    country: "USA",
    teamLeague: "Green Bay (USHL)",
    consensusRank: 27,
    shortNote: "Demo #27 — creative playmaker.",
  },
  {
    id: "dylan-ferguson",
    name: "Dylan Ferguson",
    position: "D",
    country: "CAN",
    teamLeague: "Spokane (WHL)",
    consensusRank: 28,
    shortNote: "Demo #28 — shutdown tendencies.",
  },
  {
    id: "noah-clarke",
    name: "Noah Clarke",
    position: "G",
    country: "CAN",
    teamLeague: "Guelph (OHL)",
    consensusRank: 29,
    shortNote: "Demo #29 — positional goalie.",
  },
  {
    id: "ivan-demidov",
    name: "Ivan Demidov",
    position: "RW",
    country: "RUS",
    teamLeague: "SKA Jr. (MHL)",
    consensusRank: 30,
    shortNote: "Demo #30 — high-skill winger (placeholder).",
  },
];
