/**
 * Seed prospect pool for NHL Draft 2026 Pick'em.
 *
 * Rankings below are editable seed/demo data based on public 2026 draft lists
 * (mid-2026). They are NOT final — update IDs only when replacing a prospect;
 * keep stable slugs so saved picks and scoring stay consistent.
 */
export type NhlDraft26Prospect = {
  id: string;
  name: string;
  position: string;
  country: string;
  teamLeague: string;
  consensusRank: number;
  shortNote: string;
};

/** 2026 draft class — seed rankings for development; order may change before draft day. */
export const NHL_DRAFT26_PROSPECTS_SEED: NhlDraft26Prospect[] = [
  {
    id: "gavin-mckenna",
    name: "Gavin McKenna",
    position: "LW",
    country: "CAN",
    teamLeague: "Penn State (NCAA)",
    consensusRank: 1,
    shortNote: "Seed #1 — dynamic playmaking winger, 2026 draft headliner.",
  },
  {
    id: "ivar-stenberg",
    name: "Ivar Stenberg",
    position: "LW/RW",
    country: "SWE",
    teamLeague: "Frölunda (SHL)",
    consensusRank: 2,
    shortNote: "Seed #2 — complete two-way forward with pro SHL experience.",
  },
  {
    id: "chase-reid",
    name: "Chase Reid",
    position: "D",
    country: "CAN",
    teamLeague: "Soo Greyhounds (OHL)",
    consensusRank: 3,
    shortNote: "Seed #3 — puck-moving right-shot defender.",
  },
  {
    id: "caleb-malhotra",
    name: "Caleb Malhotra",
    position: "C",
    country: "CAN",
    teamLeague: "Brantford (OHL)",
    consensusRank: 4,
    shortNote: "Seed #4 — intelligent two-way center.",
  },
  {
    id: "keaton-verhoeff",
    name: "Keaton Verhoeff",
    position: "D",
    country: "CAN",
    teamLeague: "North Dakota (NCAA)",
    consensusRank: 5,
    shortNote: "Seed #5 — big right-shot defender with top-pair upside.",
  },
  {
    id: "carson-carels",
    name: "Carson Carels",
    position: "D",
    country: "CAN",
    teamLeague: "Prince George (WHL)",
    consensusRank: 6,
    shortNote: "Seed #6 — physical, high-IQ left-shot defender.",
  },
  {
    id: "viggo-bjorck",
    name: "Viggo Björck",
    position: "C",
    country: "SWE",
    teamLeague: "Djurgården (SHL)",
    consensusRank: 7,
    shortNote: "Seed #7 — fearless SHL center with deceptive shot.",
  },
  {
    id: "alberts-smits",
    name: "Alberts Šmits",
    position: "D",
    country: "LAT",
    teamLeague: "EHC München (DEL)",
    consensusRank: 8,
    shortNote: "Seed #8 — mobile left-shot defender with pro experience.",
  },
  {
    id: "daxon-rudolph",
    name: "Daxon Rudolph",
    position: "D",
    country: "CAN",
    teamLeague: "Prince Albert (WHL)",
    consensusRank: 9,
    shortNote: "Seed #9 — two-way right-shot defender.",
  },
  {
    id: "wyatt-cullen",
    name: "Wyatt Cullen",
    position: "LW",
    country: "USA",
    teamLeague: "USNTDP",
    consensusRank: 10,
    shortNote: "Seed #10 — high-end skater and playmaker.",
  },
  {
    id: "tynan-lawrence",
    name: "Tynan Lawrence",
    position: "C",
    country: "CAN",
    teamLeague: "Boston Univ. (NCAA)",
    consensusRank: 11,
    shortNote: "Seed #11 — smart, energetic two-way forward.",
  },
  {
    id: "ryan-lin",
    name: "Ryan Lin",
    position: "D",
    country: "CAN",
    teamLeague: "Vancouver (WHL)",
    consensusRank: 12,
    shortNote: "Seed #12 — undersized puck-moving defender.",
  },
  {
    id: "alexander-command",
    name: "Alexander Command",
    position: "C",
    country: "SWE",
    teamLeague: "Örebro Jr. (SWE)",
    consensusRank: 13,
    shortNote: "Seed #13 — reliable all-situations center.",
  },
  {
    id: "ethan-belchetz",
    name: "Ethan Belchetz",
    position: "LW",
    country: "CAN",
    teamLeague: "Windsor (OHL)",
    consensusRank: 14,
    shortNote: "Seed #14 — powerful north-south winger.",
  },
  {
    id: "malte-gustafsson",
    name: "Malte Gustafsson",
    position: "D",
    country: "SWE",
    teamLeague: "HV71 (SHL)",
    consensusRank: 15,
    shortNote: "Seed #15 — large mobile defender.",
  },
  {
    id: "liam-ruck",
    name: "Liam Ruck",
    position: "RW",
    country: "CAN",
    teamLeague: "Medicine Hat (WHL)",
    consensusRank: 16,
    shortNote: "Seed #16 — goal-scoring right wing.",
  },
  {
    id: "oscar-hemming",
    name: "Oscar Hemming",
    position: "LW",
    country: "FIN",
    teamLeague: "Boston College (NCAA)",
    consensusRank: 17,
    shortNote: "Seed #17 — big skilled winger with top-six tools.",
  },
  {
    id: "adam-novotny",
    name: "Adam Novotný",
    position: "LW",
    country: "CZE",
    teamLeague: "Peterborough (OHL)",
    consensusRank: 18,
    shortNote: "Seed #18 — power forward with two-way commitment.",
  },
  {
    id: "nikita-klepov",
    name: "Nikita Klepov",
    position: "RW",
    country: "RUS",
    teamLeague: "Saginaw (OHL)",
    consensusRank: 19,
    shortNote: "Seed #19 — playmaking winger.",
  },
  {
    id: "elton-hermansson",
    name: "Elton Hermansson",
    position: "RW",
    country: "SWE",
    teamLeague: "Modo (SWE Jr.)",
    consensusRank: 20,
    shortNote: "Seed #20 — goal-oriented Swedish winger.",
  },
  {
    id: "jp-hurlbert",
    name: "J.P. Hurlbert",
    position: "LW",
    country: "CAN",
    teamLeague: "Kamloops (WHL)",
    consensusRank: 21,
    shortNote: "Seed #21 — skilled scorer with strong release.",
  },
  {
    id: "mathis-preston",
    name: "Mathis Preston",
    position: "RW",
    country: "CAN",
    teamLeague: "Vancouver (WHL)",
    consensusRank: 22,
    shortNote: "Seed #22 — NHL-ready shot and skating.",
  },
  {
    id: "ilia-morozov",
    name: "Ilia Morozov",
    position: "C",
    country: "RUS",
    teamLeague: "Miami (NCAA)",
    consensusRank: 23,
    shortNote: "Seed #23 — mature power center.",
  },
  {
    id: "markus-ruck",
    name: "Markus Ruck",
    position: "C",
    country: "CAN",
    teamLeague: "Medicine Hat (WHL)",
    consensusRank: 24,
    shortNote: "Seed #24 — hardworking playmaking center.",
  },
  {
    id: "egor-shilov",
    name: "Egor Shilov",
    position: "C",
    country: "RUS",
    teamLeague: "Victoriaville (QMJHL)",
    consensusRank: 25,
    shortNote: "Seed #25 — skilled QMJHL pivot.",
  },
  {
    id: "oliver-suvanto",
    name: "Oliver Suvanto",
    position: "C",
    country: "FIN",
    teamLeague: "Tappara (FIN Jr.)",
    consensusRank: 26,
    shortNote: "Seed #26 — responsible two-way center.",
  },
  {
    id: "tommy-bleyl",
    name: "Tommy Bleyl",
    position: "D",
    country: "CAN",
    teamLeague: "Moncton (QMJHL)",
    consensusRank: 27,
    shortNote: "Seed #27 — offensive right-shot defender.",
  },
  {
    id: "maddox-dagenais",
    name: "Maddox Dagenais",
    position: "C",
    country: "CAN",
    teamLeague: "Quebec (QMJHL)",
    consensusRank: 28,
    shortNote: "Seed #28 — big two-way forward.",
  },
  {
    id: "xavier-villeneuve",
    name: "Xavier Villeneuve",
    position: "D",
    country: "CAN",
    teamLeague: "Blainville-Boisbriand (QMJHL)",
    consensusRank: 29,
    shortNote: "Seed #29 — puck-moving left-shot defender.",
  },
  {
    id: "ryan-roobroeck",
    name: "Ryan Roobroeck",
    position: "LW",
    country: "CAN",
    teamLeague: "Niagara (OHL)",
    consensusRank: 30,
    shortNote: "Seed #30 — large goal-scoring winger.",
  },
];
